<?xml version="1.0" encoding="utf-8" ?>
<ogr:FeatureCollection
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://ogr.maptools.org/ States.xsd"
     xmlns:ogr="http://ogr.maptools.org/"
     xmlns:gml="http://www.opengis.net/gml">
  <gml:boundedBy>
    <gml:Box>
      <gml:coord><gml:X>-127.25</gml:X><gml:Y>27.8744</gml:Y></gml:coord>
      <gml:coord><gml:X>-68.98009999999999</gml:X><gml:Y>49.25</gml:Y></gml:coord>
    </gml:Box>
  </gml:boundedBy>
                                                                                                                               
  <gml:featureMember>
    <ogr:States fid="States.0">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-86.7509,32.5901</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>3615</ogr:Population>
      <ogr:Income>3624</ogr:Income>
      <ogr:Illiteracy>2.1</ogr:Illiteracy>
      <ogr:Life.Exp>69.05</ogr:Life.Exp>
      <ogr:Murder>15.1</ogr:Murder>
      <ogr:HS.Grad>41.3</ogr:HS.Grad>
      <ogr:Frost>20</ogr:Frost>
      <ogr:Area>50708</ogr:Area>
      <ogr:Name>Alabama</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.1">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-127.25,49.25</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>365</ogr:Population>
      <ogr:Income>6315</ogr:Income>
      <ogr:Illiteracy>1.5</ogr:Illiteracy>
      <ogr:Life.Exp>69.31</ogr:Life.Exp>
      <ogr:Murder>11.3</ogr:Murder>
      <ogr:HS.Grad>66.7</ogr:HS.Grad>
      <ogr:Frost>152</ogr:Frost>
      <ogr:Area>566432</ogr:Area>
      <ogr:Name>Alaska</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.2">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-111.625,34.2192</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2212</ogr:Population>
      <ogr:Income>4530</ogr:Income>
      <ogr:Illiteracy>1.8</ogr:Illiteracy>
      <ogr:Life.Exp>70.55</ogr:Life.Exp>
      <ogr:Murder>7.8</ogr:Murder>
      <ogr:HS.Grad>58.1</ogr:HS.Grad>
      <ogr:Frost>15</ogr:Frost>
      <ogr:Area>113417</ogr:Area>
      <ogr:Name>Arizona</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.3">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-92.2992,34.7336</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2110</ogr:Population>
      <ogr:Income>3378</ogr:Income>
      <ogr:Illiteracy>1.9</ogr:Illiteracy>
      <ogr:Life.Exp>70.66</ogr:Life.Exp>
      <ogr:Murder>10.1</ogr:Murder>
      <ogr:HS.Grad>39.9</ogr:HS.Grad>
      <ogr:Frost>65</ogr:Frost>
      <ogr:Area>51945</ogr:Area>
      <ogr:Name>Arkansas</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.4">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-119.773,36.5341</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>21198</ogr:Population>
      <ogr:Income>5114</ogr:Income>
      <ogr:Illiteracy>1.1</ogr:Illiteracy>
      <ogr:Life.Exp>71.71</ogr:Life.Exp>
      <ogr:Murder>10.3</ogr:Murder>
      <ogr:HS.Grad>62.6</ogr:HS.Grad>
      <ogr:Frost>20</ogr:Frost>
      <ogr:Area>156361</ogr:Area>
      <ogr:Name>California</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.5">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-105.513,38.6777</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2541</ogr:Population>
      <ogr:Income>4884</ogr:Income>
      <ogr:Illiteracy>0.7</ogr:Illiteracy>
      <ogr:Life.Exp>72.06</ogr:Life.Exp>
      <ogr:Murder>6.8</ogr:Murder>
      <ogr:HS.Grad>63.9</ogr:HS.Grad>
      <ogr:Frost>166</ogr:Frost>
      <ogr:Area>103766</ogr:Area>
      <ogr:Name>Colorado</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.6">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-72.3573,41.5928</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>3100</ogr:Population>
      <ogr:Income>5348</ogr:Income>
      <ogr:Illiteracy>1.1</ogr:Illiteracy>
      <ogr:Life.Exp>72.48</ogr:Life.Exp>
      <ogr:Murder>3.1</ogr:Murder>
      <ogr:HS.Grad>56</ogr:HS.Grad>
      <ogr:Frost>139</ogr:Frost>
      <ogr:Area>4862</ogr:Area>
      <ogr:Name>Connecticut</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.7">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-74.9841,38.6777</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>579</ogr:Population>
      <ogr:Income>4809</ogr:Income>
      <ogr:Illiteracy>0.9</ogr:Illiteracy>
      <ogr:Life.Exp>70.06</ogr:Life.Exp>
      <ogr:Murder>6.2</ogr:Murder>
      <ogr:HS.Grad>54.6</ogr:HS.Grad>
      <ogr:Frost>103</ogr:Frost>
      <ogr:Area>1982</ogr:Area>
      <ogr:Name>Delaware</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.8">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-81.685,27.8744</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>8277</ogr:Population>
      <ogr:Income>4815</ogr:Income>
      <ogr:Illiteracy>1.3</ogr:Illiteracy>
      <ogr:Life.Exp>70.66</ogr:Life.Exp>
      <ogr:Murder>10.7</ogr:Murder>
      <ogr:HS.Grad>52.6</ogr:HS.Grad>
      <ogr:Frost>11</ogr:Frost>
      <ogr:Area>54090</ogr:Area>
      <ogr:Name>Florida</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.9">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-83.3736,32.3329</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>4931</ogr:Population>
      <ogr:Income>4091</ogr:Income>
      <ogr:Illiteracy>2</ogr:Illiteracy>
      <ogr:Life.Exp>68.54</ogr:Life.Exp>
      <ogr:Murder>13.9</ogr:Murder>
      <ogr:HS.Grad>40.6</ogr:HS.Grad>
      <ogr:Frost>60</ogr:Frost>
      <ogr:Area>58073</ogr:Area>
      <ogr:Name>Georgia</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.10">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-126.25,31.75</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>868</ogr:Population>
      <ogr:Income>4963</ogr:Income>
      <ogr:Illiteracy>1.9</ogr:Illiteracy>
      <ogr:Life.Exp>73.6</ogr:Life.Exp>
      <ogr:Murder>6.2</ogr:Murder>
      <ogr:HS.Grad>61.9</ogr:HS.Grad>
      <ogr:Frost>0</ogr:Frost>
      <ogr:Area>6425</ogr:Area>
      <ogr:Name>Hawaii</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.11">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-113.93,43.5648</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>813</ogr:Population>
      <ogr:Income>4119</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>71.87</ogr:Life.Exp>
      <ogr:Murder>5.3</ogr:Murder>
      <ogr:HS.Grad>59.5</ogr:HS.Grad>
      <ogr:Frost>126</ogr:Frost>
      <ogr:Area>82677</ogr:Area>
      <ogr:Name>Idaho</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.12">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-89.3776,40.0495</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>11197</ogr:Population>
      <ogr:Income>5107</ogr:Income>
      <ogr:Illiteracy>0.9</ogr:Illiteracy>
      <ogr:Life.Exp>70.14</ogr:Life.Exp>
      <ogr:Murder>10.3</ogr:Murder>
      <ogr:HS.Grad>52.6</ogr:HS.Grad>
      <ogr:Frost>127</ogr:Frost>
      <ogr:Area>55748</ogr:Area>
      <ogr:Name>Illinois</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.13">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-86.0808,40.0495</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>5313</ogr:Population>
      <ogr:Income>4458</ogr:Income>
      <ogr:Illiteracy>0.7</ogr:Illiteracy>
      <ogr:Life.Exp>70.88</ogr:Life.Exp>
      <ogr:Murder>7.1</ogr:Murder>
      <ogr:HS.Grad>52.9</ogr:HS.Grad>
      <ogr:Frost>122</ogr:Frost>
      <ogr:Area>36097</ogr:Area>
      <ogr:Name>Indiana</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.14">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-93.3714,41.9358</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2861</ogr:Population>
      <ogr:Income>4628</ogr:Income>
      <ogr:Illiteracy>0.5</ogr:Illiteracy>
      <ogr:Life.Exp>72.56</ogr:Life.Exp>
      <ogr:Murder>2.3</ogr:Murder>
      <ogr:HS.Grad>59</ogr:HS.Grad>
      <ogr:Frost>140</ogr:Frost>
      <ogr:Area>55941</ogr:Area>
      <ogr:Name>Iowa</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.15">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-98.1156,38.4204</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2280</ogr:Population>
      <ogr:Income>4669</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>72.58</ogr:Life.Exp>
      <ogr:Murder>4.5</ogr:Murder>
      <ogr:HS.Grad>59.9</ogr:HS.Grad>
      <ogr:Frost>114</ogr:Frost>
      <ogr:Area>81787</ogr:Area>
      <ogr:Name>Kansas</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.16">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-84.7674,37.3915</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>3387</ogr:Population>
      <ogr:Income>3712</ogr:Income>
      <ogr:Illiteracy>1.6</ogr:Illiteracy>
      <ogr:Life.Exp>70.1</ogr:Life.Exp>
      <ogr:Murder>10.6</ogr:Murder>
      <ogr:HS.Grad>38.5</ogr:HS.Grad>
      <ogr:Frost>95</ogr:Frost>
      <ogr:Area>39650</ogr:Area>
      <ogr:Name>Kentucky</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.17">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-92.2724,30.6181</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>3806</ogr:Population>
      <ogr:Income>3545</ogr:Income>
      <ogr:Illiteracy>2.8</ogr:Illiteracy>
      <ogr:Life.Exp>68.76</ogr:Life.Exp>
      <ogr:Murder>13.2</ogr:Murder>
      <ogr:HS.Grad>42.2</ogr:HS.Grad>
      <ogr:Frost>12</ogr:Frost>
      <ogr:Area>44930</ogr:Area>
      <ogr:Name>Louisiana</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.18">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-68.9801,45.6226</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>1058</ogr:Population>
      <ogr:Income>3694</ogr:Income>
      <ogr:Illiteracy>0.7</ogr:Illiteracy>
      <ogr:Life.Exp>70.39</ogr:Life.Exp>
      <ogr:Murder>2.7</ogr:Murder>
      <ogr:HS.Grad>54.7</ogr:HS.Grad>
      <ogr:Frost>161</ogr:Frost>
      <ogr:Area>30920</ogr:Area>
      <ogr:Name>Maine</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.19">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-76.6459,39.2778</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>4122</ogr:Population>
      <ogr:Income>5299</ogr:Income>
      <ogr:Illiteracy>0.9</ogr:Illiteracy>
      <ogr:Life.Exp>70.22</ogr:Life.Exp>
      <ogr:Murder>8.5</ogr:Murder>
      <ogr:HS.Grad>52.3</ogr:HS.Grad>
      <ogr:Frost>101</ogr:Frost>
      <ogr:Area>9891</ogr:Area>
      <ogr:Name>Maryland</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.20">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-71.58,42.3645</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>5814</ogr:Population>
      <ogr:Income>4755</ogr:Income>
      <ogr:Illiteracy>1.1</ogr:Illiteracy>
      <ogr:Life.Exp>71.83</ogr:Life.Exp>
      <ogr:Murder>3.3</ogr:Murder>
      <ogr:HS.Grad>58.5</ogr:HS.Grad>
      <ogr:Frost>103</ogr:Frost>
      <ogr:Area>7826</ogr:Area>
      <ogr:Name>Massachusetts</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.21">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-84.687,43.1361</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>9111</ogr:Population>
      <ogr:Income>4751</ogr:Income>
      <ogr:Illiteracy>0.9</ogr:Illiteracy>
      <ogr:Life.Exp>70.63</ogr:Life.Exp>
      <ogr:Murder>11.1</ogr:Murder>
      <ogr:HS.Grad>52.8</ogr:HS.Grad>
      <ogr:Frost>125</ogr:Frost>
      <ogr:Area>56817</ogr:Area>
      <ogr:Name>Michigan</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.22">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-94.6043,46.3943</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>3921</ogr:Population>
      <ogr:Income>4675</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>72.96</ogr:Life.Exp>
      <ogr:Murder>2.3</ogr:Murder>
      <ogr:HS.Grad>57.6</ogr:HS.Grad>
      <ogr:Frost>160</ogr:Frost>
      <ogr:Area>79289</ogr:Area>
      <ogr:Name>Minnesota</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.23">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-89.8065,32.6758</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2341</ogr:Population>
      <ogr:Income>3098</ogr:Income>
      <ogr:Illiteracy>2.4</ogr:Illiteracy>
      <ogr:Life.Exp>68.09</ogr:Life.Exp>
      <ogr:Murder>12.5</ogr:Murder>
      <ogr:HS.Grad>41</ogr:HS.Grad>
      <ogr:Frost>50</ogr:Frost>
      <ogr:Area>47296</ogr:Area>
      <ogr:Name>Mississippi</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.24">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-92.5137,38.3347</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>4767</ogr:Population>
      <ogr:Income>4254</ogr:Income>
      <ogr:Illiteracy>0.8</ogr:Illiteracy>
      <ogr:Life.Exp>70.69</ogr:Life.Exp>
      <ogr:Murder>9.3</ogr:Murder>
      <ogr:HS.Grad>48.8</ogr:HS.Grad>
      <ogr:Frost>108</ogr:Frost>
      <ogr:Area>68995</ogr:Area>
      <ogr:Name>Missouri</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.25">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-109.32,46.823</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>746</ogr:Population>
      <ogr:Income>4347</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>70.56</ogr:Life.Exp>
      <ogr:Murder>5</ogr:Murder>
      <ogr:HS.Grad>59.2</ogr:HS.Grad>
      <ogr:Frost>155</ogr:Frost>
      <ogr:Area>145587</ogr:Area>
      <ogr:Name>Montana</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.26">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-99.5898,41.3356</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>1544</ogr:Population>
      <ogr:Income>4508</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>72.6</ogr:Life.Exp>
      <ogr:Murder>2.9</ogr:Murder>
      <ogr:HS.Grad>59.3</ogr:HS.Grad>
      <ogr:Frost>139</ogr:Frost>
      <ogr:Area>76483</ogr:Area>
      <ogr:Name>Nebraska</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.27">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-116.851,39.1063</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>590</ogr:Population>
      <ogr:Income>5149</ogr:Income>
      <ogr:Illiteracy>0.5</ogr:Illiteracy>
      <ogr:Life.Exp>69.03</ogr:Life.Exp>
      <ogr:Murder>11.5</ogr:Murder>
      <ogr:HS.Grad>65.2</ogr:HS.Grad>
      <ogr:Frost>188</ogr:Frost>
      <ogr:Area>109889</ogr:Area>
      <ogr:Name>Nevada</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.28">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-71.3924,43.3934</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>812</ogr:Population>
      <ogr:Income>4281</ogr:Income>
      <ogr:Illiteracy>0.7</ogr:Illiteracy>
      <ogr:Life.Exp>71.23</ogr:Life.Exp>
      <ogr:Murder>3.3</ogr:Murder>
      <ogr:HS.Grad>57.6</ogr:HS.Grad>
      <ogr:Frost>174</ogr:Frost>
      <ogr:Area>9027</ogr:Area>
      <ogr:Name>New Hampshire</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.29">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-74.2336,39.9637</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>7333</ogr:Population>
      <ogr:Income>5237</ogr:Income>
      <ogr:Illiteracy>1.1</ogr:Illiteracy>
      <ogr:Life.Exp>70.93</ogr:Life.Exp>
      <ogr:Murder>5.2</ogr:Murder>
      <ogr:HS.Grad>52.5</ogr:HS.Grad>
      <ogr:Frost>115</ogr:Frost>
      <ogr:Area>7521</ogr:Area>
      <ogr:Name>New Jersey</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.30">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-105.942,34.4764</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>1144</ogr:Population>
      <ogr:Income>3601</ogr:Income>
      <ogr:Illiteracy>2.2</ogr:Illiteracy>
      <ogr:Life.Exp>70.32</ogr:Life.Exp>
      <ogr:Murder>9.7</ogr:Murder>
      <ogr:HS.Grad>55.2</ogr:HS.Grad>
      <ogr:Frost>120</ogr:Frost>
      <ogr:Area>121412</ogr:Area>
      <ogr:Name>New Mexico</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.31">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-75.1449,43.1361</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>18076</ogr:Population>
      <ogr:Income>4903</ogr:Income>
      <ogr:Illiteracy>1.4</ogr:Illiteracy>
      <ogr:Life.Exp>70.55</ogr:Life.Exp>
      <ogr:Murder>10.9</ogr:Murder>
      <ogr:HS.Grad>52.7</ogr:HS.Grad>
      <ogr:Frost>82</ogr:Frost>
      <ogr:Area>47831</ogr:Area>
      <ogr:Name>New York</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.32">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-78.4686,35.4195</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>5441</ogr:Population>
      <ogr:Income>3875</ogr:Income>
      <ogr:Illiteracy>1.8</ogr:Illiteracy>
      <ogr:Life.Exp>69.21</ogr:Life.Exp>
      <ogr:Murder>11.1</ogr:Murder>
      <ogr:HS.Grad>38.5</ogr:HS.Grad>
      <ogr:Frost>80</ogr:Frost>
      <ogr:Area>48798</ogr:Area>
      <ogr:Name>North Carolina</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.33">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-100.099,47.2517</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>637</ogr:Population>
      <ogr:Income>5087</ogr:Income>
      <ogr:Illiteracy>0.8</ogr:Illiteracy>
      <ogr:Life.Exp>72.78</ogr:Life.Exp>
      <ogr:Murder>1.4</ogr:Murder>
      <ogr:HS.Grad>50.3</ogr:HS.Grad>
      <ogr:Frost>186</ogr:Frost>
      <ogr:Area>69273</ogr:Area>
      <ogr:Name>North Dakota</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.34">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-82.5963,40.221</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>10735</ogr:Population>
      <ogr:Income>4561</ogr:Income>
      <ogr:Illiteracy>0.8</ogr:Illiteracy>
      <ogr:Life.Exp>70.82</ogr:Life.Exp>
      <ogr:Murder>7.4</ogr:Murder>
      <ogr:HS.Grad>53.2</ogr:HS.Grad>
      <ogr:Frost>124</ogr:Frost>
      <ogr:Area>40975</ogr:Area>
      <ogr:Name>Ohio</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.35">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-97.1239,35.5053</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2715</ogr:Population>
      <ogr:Income>3983</ogr:Income>
      <ogr:Illiteracy>1.1</ogr:Illiteracy>
      <ogr:Life.Exp>71.42</ogr:Life.Exp>
      <ogr:Murder>6.4</ogr:Murder>
      <ogr:HS.Grad>51.6</ogr:HS.Grad>
      <ogr:Frost>82</ogr:Frost>
      <ogr:Area>68782</ogr:Area>
      <ogr:Name>Oklahoma</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.36">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-120.068,43.9078</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2284</ogr:Population>
      <ogr:Income>4660</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>72.13</ogr:Life.Exp>
      <ogr:Murder>4.2</ogr:Murder>
      <ogr:HS.Grad>60</ogr:HS.Grad>
      <ogr:Frost>44</ogr:Frost>
      <ogr:Area>96184</ogr:Area>
      <ogr:Name>Oregon</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.37">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-77.45,40.9069</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>11860</ogr:Population>
      <ogr:Income>4449</ogr:Income>
      <ogr:Illiteracy>1</ogr:Illiteracy>
      <ogr:Life.Exp>70.43</ogr:Life.Exp>
      <ogr:Murder>6.1</ogr:Murder>
      <ogr:HS.Grad>50.2</ogr:HS.Grad>
      <ogr:Frost>126</ogr:Frost>
      <ogr:Area>44966</ogr:Area>
      <ogr:Name>Pennsylvania</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.38">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-71.1244,41.5928</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>931</ogr:Population>
      <ogr:Income>4558</ogr:Income>
      <ogr:Illiteracy>1.3</ogr:Illiteracy>
      <ogr:Life.Exp>71.9</ogr:Life.Exp>
      <ogr:Murder>2.4</ogr:Murder>
      <ogr:HS.Grad>46.4</ogr:HS.Grad>
      <ogr:Frost>127</ogr:Frost>
      <ogr:Area>1049</ogr:Area>
      <ogr:Name>Rhode Island</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.39">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-80.5056,33.619</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2816</ogr:Population>
      <ogr:Income>3635</ogr:Income>
      <ogr:Illiteracy>2.3</ogr:Illiteracy>
      <ogr:Life.Exp>67.96</ogr:Life.Exp>
      <ogr:Murder>11.6</ogr:Murder>
      <ogr:HS.Grad>37.8</ogr:HS.Grad>
      <ogr:Frost>65</ogr:Frost>
      <ogr:Area>30225</ogr:Area>
      <ogr:Name>South Carolina</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.40">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-99.7238,44.3365</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>681</ogr:Population>
      <ogr:Income>4167</ogr:Income>
      <ogr:Illiteracy>0.5</ogr:Illiteracy>
      <ogr:Life.Exp>72.08</ogr:Life.Exp>
      <ogr:Murder>1.7</ogr:Murder>
      <ogr:HS.Grad>53.3</ogr:HS.Grad>
      <ogr:Frost>172</ogr:Frost>
      <ogr:Area>75955</ogr:Area>
      <ogr:Name>South Dakota</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.41">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-86.456,35.6767</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>4173</ogr:Population>
      <ogr:Income>3821</ogr:Income>
      <ogr:Illiteracy>1.7</ogr:Illiteracy>
      <ogr:Life.Exp>70.11</ogr:Life.Exp>
      <ogr:Murder>11</ogr:Murder>
      <ogr:HS.Grad>41.8</ogr:HS.Grad>
      <ogr:Frost>70</ogr:Frost>
      <ogr:Area>41328</ogr:Area>
      <ogr:Name>Tennessee</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.42">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-98.7857,31.3897</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>12237</ogr:Population>
      <ogr:Income>4188</ogr:Income>
      <ogr:Illiteracy>2.2</ogr:Illiteracy>
      <ogr:Life.Exp>70.9</ogr:Life.Exp>
      <ogr:Murder>12.2</ogr:Murder>
      <ogr:HS.Grad>47.4</ogr:HS.Grad>
      <ogr:Frost>35</ogr:Frost>
      <ogr:Area>262134</ogr:Area>
      <ogr:Name>Texas</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.43">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-111.33,39.1063</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>1203</ogr:Population>
      <ogr:Income>4022</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>72.9</ogr:Life.Exp>
      <ogr:Murder>4.5</ogr:Murder>
      <ogr:HS.Grad>67.3</ogr:HS.Grad>
      <ogr:Frost>137</ogr:Frost>
      <ogr:Area>82096</ogr:Area>
      <ogr:Name>Utah</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.44">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-72.545,44.2508</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>472</ogr:Population>
      <ogr:Income>3907</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>71.64</ogr:Life.Exp>
      <ogr:Murder>5.5</ogr:Murder>
      <ogr:HS.Grad>57.1</ogr:HS.Grad>
      <ogr:Frost>168</ogr:Frost>
      <ogr:Area>9267</ogr:Area>
      <ogr:Name>Vermont</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.45">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-78.2005,37.563</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>4981</ogr:Population>
      <ogr:Income>4701</ogr:Income>
      <ogr:Illiteracy>1.4</ogr:Illiteracy>
      <ogr:Life.Exp>70.08</ogr:Life.Exp>
      <ogr:Murder>9.5</ogr:Murder>
      <ogr:HS.Grad>47.8</ogr:HS.Grad>
      <ogr:Frost>85</ogr:Frost>
      <ogr:Area>39780</ogr:Area>
      <ogr:Name>Virginia</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.46">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-119.746,47.4231</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>3559</ogr:Population>
      <ogr:Income>4864</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>71.72</ogr:Life.Exp>
      <ogr:Murder>4.3</ogr:Murder>
      <ogr:HS.Grad>63.5</ogr:HS.Grad>
      <ogr:Frost>32</ogr:Frost>
      <ogr:Area>66570</ogr:Area>
      <ogr:Name>Washington</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.47">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-80.6665,38.4204</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>1799</ogr:Population>
      <ogr:Income>3617</ogr:Income>
      <ogr:Illiteracy>1.4</ogr:Illiteracy>
      <ogr:Life.Exp>69.48</ogr:Life.Exp>
      <ogr:Murder>6.7</ogr:Murder>
      <ogr:HS.Grad>41.6</ogr:HS.Grad>
      <ogr:Frost>100</ogr:Frost>
      <ogr:Area>24070</ogr:Area>
      <ogr:Name>West Virginia</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.48">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-89.9941,44.5937</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>4589</ogr:Population>
      <ogr:Income>4468</ogr:Income>
      <ogr:Illiteracy>0.7</ogr:Illiteracy>
      <ogr:Life.Exp>72.48</ogr:Life.Exp>
      <ogr:Murder>3</ogr:Murder>
      <ogr:HS.Grad>54.5</ogr:HS.Grad>
      <ogr:Frost>149</ogr:Frost>
      <ogr:Area>54464</ogr:Area>
      <ogr:Name>Wisconsin</ogr:Name>
    </ogr:States>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:States fid="States.49">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-107.256,43.0504</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>376</ogr:Population>
      <ogr:Income>4566</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>70.29</ogr:Life.Exp>
      <ogr:Murder>6.9</ogr:Murder>
      <ogr:HS.Grad>62.9</ogr:HS.Grad>
      <ogr:Frost>173</ogr:Frost>
      <ogr:Area>97203</ogr:Area>
      <ogr:Name>Wyoming</ogr:Name>
    </ogr:States>
  </gml:featureMember>
</ogr:FeatureCollection>
