<?xml version="1.0" encoding="utf-8" ?>
<ogr:FeatureCollection
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://ogr.maptools.org/state.xsd"
     xmlns:ogr="http://ogr.maptools.org/"
     xmlns:gml="http://www.opengis.net/gml">
  <gml:boundedBy>
    <gml:Box>
      <gml:coord><gml:X>-127.25</gml:X><gml:Y>27.8744</gml:Y></gml:coord>
      <gml:coord><gml:X>-68.98009999999999</gml:X><gml:Y>49.25</gml:Y></gml:coord>
    </gml:Box>
  </gml:boundedBy>                                                          
  <gml:featureMember>
    <ogr:state fid="F0">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-86.7509,32.5901</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>3615</ogr:Population>
      <ogr:Income>3624</ogr:Income>
      <ogr:Illiteracy>2.1</ogr:Illiteracy>
      <ogr:Life.Exp>69.05</ogr:Life.Exp>
      <ogr:Murder>15.1</ogr:Murder>
      <ogr:HS.Grad>41.3</ogr:HS.Grad>
      <ogr:Frost>20</ogr:Frost>
      <ogr:Area>50708</ogr:Area>
      <ogr:Name>Alabama</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F1">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-127.25,49.25</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>365</ogr:Population>
      <ogr:Income>6315</ogr:Income>
      <ogr:Illiteracy>1.5</ogr:Illiteracy>
      <ogr:Life.Exp>69.31</ogr:Life.Exp>
      <ogr:Murder>11.3</ogr:Murder>
      <ogr:HS.Grad>66.7</ogr:HS.Grad>
      <ogr:Frost>152</ogr:Frost>
      <ogr:Area>566432</ogr:Area>
      <ogr:Name>Alaska</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F2">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-111.625,34.2192</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2212</ogr:Population>
      <ogr:Income>4530</ogr:Income>
      <ogr:Illiteracy>1.8</ogr:Illiteracy>
      <ogr:Life.Exp>70.55</ogr:Life.Exp>
      <ogr:Murder>7.8</ogr:Murder>
      <ogr:HS.Grad>58.1</ogr:HS.Grad>
      <ogr:Frost>15</ogr:Frost>
      <ogr:Area>113417</ogr:Area>
      <ogr:Name>Arizona</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F3">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-92.299199999999999,34.733600000000003</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2110</ogr:Population>
      <ogr:Income>3378</ogr:Income>
      <ogr:Illiteracy>1.9</ogr:Illiteracy>
      <ogr:Life.Exp>70.66</ogr:Life.Exp>
      <ogr:Murder>10.1</ogr:Murder>
      <ogr:HS.Grad>39.9</ogr:HS.Grad>
      <ogr:Frost>65</ogr:Frost>
      <ogr:Area>51945</ogr:Area>
      <ogr:Name>Arkansas</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F4">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-119.772999999999996,36.534100000000002</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>21198</ogr:Population>
      <ogr:Income>5114</ogr:Income>
      <ogr:Illiteracy>1.1</ogr:Illiteracy>
      <ogr:Life.Exp>71.71</ogr:Life.Exp>
      <ogr:Murder>10.3</ogr:Murder>
      <ogr:HS.Grad>62.6</ogr:HS.Grad>
      <ogr:Frost>20</ogr:Frost>
      <ogr:Area>156361</ogr:Area>
      <ogr:Name>California</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F5">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-105.513000000000005,38.677700000000002</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2541</ogr:Population>
      <ogr:Income>4884</ogr:Income>
      <ogr:Illiteracy>0.7</ogr:Illiteracy>
      <ogr:Life.Exp>72.06</ogr:Life.Exp>
      <ogr:Murder>6.8</ogr:Murder>
      <ogr:HS.Grad>63.9</ogr:HS.Grad>
      <ogr:Frost>166</ogr:Frost>
      <ogr:Area>103766</ogr:Area>
      <ogr:Name>Colorado</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F6">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-72.357299999999995,41.592799999999997</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>3100</ogr:Population>
      <ogr:Income>5348</ogr:Income>
      <ogr:Illiteracy>1.1</ogr:Illiteracy>
      <ogr:Life.Exp>72.48</ogr:Life.Exp>
      <ogr:Murder>3.1</ogr:Murder>
      <ogr:HS.Grad>56</ogr:HS.Grad>
      <ogr:Frost>139</ogr:Frost>
      <ogr:Area>4862</ogr:Area>
      <ogr:Name>Connecticut</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F7">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-74.984099999999998,38.677700000000002</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>579</ogr:Population>
      <ogr:Income>4809</ogr:Income>
      <ogr:Illiteracy>0.9</ogr:Illiteracy>
      <ogr:Life.Exp>70.06</ogr:Life.Exp>
      <ogr:Murder>6.2</ogr:Murder>
      <ogr:HS.Grad>54.6</ogr:HS.Grad>
      <ogr:Frost>103</ogr:Frost>
      <ogr:Area>1982</ogr:Area>
      <ogr:Name>Delaware</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F8">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-81.685000000000002,27.8744</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>8277</ogr:Population>
      <ogr:Income>4815</ogr:Income>
      <ogr:Illiteracy>1.3</ogr:Illiteracy>
      <ogr:Life.Exp>70.66</ogr:Life.Exp>
      <ogr:Murder>10.7</ogr:Murder>
      <ogr:HS.Grad>52.6</ogr:HS.Grad>
      <ogr:Frost>11</ogr:Frost>
      <ogr:Area>54090</ogr:Area>
      <ogr:Name>Florida</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F9">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-83.373599999999996,32.332900000000002</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>4931</ogr:Population>
      <ogr:Income>4091</ogr:Income>
      <ogr:Illiteracy>2</ogr:Illiteracy>
      <ogr:Life.Exp>68.54</ogr:Life.Exp>
      <ogr:Murder>13.9</ogr:Murder>
      <ogr:HS.Grad>40.6</ogr:HS.Grad>
      <ogr:Frost>60</ogr:Frost>
      <ogr:Area>58073</ogr:Area>
      <ogr:Name>Georgia</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F10">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-126.25,31.75</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>868</ogr:Population>
      <ogr:Income>4963</ogr:Income>
      <ogr:Illiteracy>1.9</ogr:Illiteracy>
      <ogr:Life.Exp>73.6</ogr:Life.Exp>
      <ogr:Murder>6.2</ogr:Murder>
      <ogr:HS.Grad>61.9</ogr:HS.Grad>
      <ogr:Frost>0</ogr:Frost>
      <ogr:Area>6425</ogr:Area>
      <ogr:Name>Hawaii</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F11">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-113.930000000000007,43.564799999999998</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>813</ogr:Population>
      <ogr:Income>4119</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>71.87</ogr:Life.Exp>
      <ogr:Murder>5.3</ogr:Murder>
      <ogr:HS.Grad>59.5</ogr:HS.Grad>
      <ogr:Frost>126</ogr:Frost>
      <ogr:Area>82677</ogr:Area>
      <ogr:Name>Idaho</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F12">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-89.3776,40.049500000000002</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>11197</ogr:Population>
      <ogr:Income>5107</ogr:Income>
      <ogr:Illiteracy>0.9</ogr:Illiteracy>
      <ogr:Life.Exp>70.14</ogr:Life.Exp>
      <ogr:Murder>10.3</ogr:Murder>
      <ogr:HS.Grad>52.6</ogr:HS.Grad>
      <ogr:Frost>127</ogr:Frost>
      <ogr:Area>55748</ogr:Area>
      <ogr:Name>Illinois</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F13">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-86.080799999999996,40.049500000000002</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>5313</ogr:Population>
      <ogr:Income>4458</ogr:Income>
      <ogr:Illiteracy>0.7</ogr:Illiteracy>
      <ogr:Life.Exp>70.88</ogr:Life.Exp>
      <ogr:Murder>7.1</ogr:Murder>
      <ogr:HS.Grad>52.9</ogr:HS.Grad>
      <ogr:Frost>122</ogr:Frost>
      <ogr:Area>36097</ogr:Area>
      <ogr:Name>Indiana</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F14">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-93.371399999999994,41.9358</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2861</ogr:Population>
      <ogr:Income>4628</ogr:Income>
      <ogr:Illiteracy>0.5</ogr:Illiteracy>
      <ogr:Life.Exp>72.56</ogr:Life.Exp>
      <ogr:Murder>2.3</ogr:Murder>
      <ogr:HS.Grad>59</ogr:HS.Grad>
      <ogr:Frost>140</ogr:Frost>
      <ogr:Area>55941</ogr:Area>
      <ogr:Name>Iowa</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F15">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-98.1156,38.4204</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2280</ogr:Population>
      <ogr:Income>4669</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>72.58</ogr:Life.Exp>
      <ogr:Murder>4.5</ogr:Murder>
      <ogr:HS.Grad>59.9</ogr:HS.Grad>
      <ogr:Frost>114</ogr:Frost>
      <ogr:Area>81787</ogr:Area>
      <ogr:Name>Kansas</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F16">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-84.767399999999995,37.3915</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>3387</ogr:Population>
      <ogr:Income>3712</ogr:Income>
      <ogr:Illiteracy>1.6</ogr:Illiteracy>
      <ogr:Life.Exp>70.1</ogr:Life.Exp>
      <ogr:Murder>10.6</ogr:Murder>
      <ogr:HS.Grad>38.5</ogr:HS.Grad>
      <ogr:Frost>95</ogr:Frost>
      <ogr:Area>39650</ogr:Area>
      <ogr:Name>Kentucky</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F17">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-92.272400000000005,30.618099999999998</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>3806</ogr:Population>
      <ogr:Income>3545</ogr:Income>
      <ogr:Illiteracy>2.8</ogr:Illiteracy>
      <ogr:Life.Exp>68.76</ogr:Life.Exp>
      <ogr:Murder>13.2</ogr:Murder>
      <ogr:HS.Grad>42.2</ogr:HS.Grad>
      <ogr:Frost>12</ogr:Frost>
      <ogr:Area>44930</ogr:Area>
      <ogr:Name>Louisiana</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F18">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-68.980099999999993,45.622599999999998</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>1058</ogr:Population>
      <ogr:Income>3694</ogr:Income>
      <ogr:Illiteracy>0.7</ogr:Illiteracy>
      <ogr:Life.Exp>70.39</ogr:Life.Exp>
      <ogr:Murder>2.7</ogr:Murder>
      <ogr:HS.Grad>54.7</ogr:HS.Grad>
      <ogr:Frost>161</ogr:Frost>
      <ogr:Area>30920</ogr:Area>
      <ogr:Name>Maine</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F19">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-76.645899999999997,39.277799999999999</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>4122</ogr:Population>
      <ogr:Income>5299</ogr:Income>
      <ogr:Illiteracy>0.9</ogr:Illiteracy>
      <ogr:Life.Exp>70.22</ogr:Life.Exp>
      <ogr:Murder>8.5</ogr:Murder>
      <ogr:HS.Grad>52.3</ogr:HS.Grad>
      <ogr:Frost>101</ogr:Frost>
      <ogr:Area>9891</ogr:Area>
      <ogr:Name>Maryland</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F20">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-71.579999999999998,42.3645</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>5814</ogr:Population>
      <ogr:Income>4755</ogr:Income>
      <ogr:Illiteracy>1.1</ogr:Illiteracy>
      <ogr:Life.Exp>71.83</ogr:Life.Exp>
      <ogr:Murder>3.3</ogr:Murder>
      <ogr:HS.Grad>58.5</ogr:HS.Grad>
      <ogr:Frost>103</ogr:Frost>
      <ogr:Area>7826</ogr:Area>
      <ogr:Name>Massachusetts</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F21">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-84.686999999999998,43.136099999999999</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>9111</ogr:Population>
      <ogr:Income>4751</ogr:Income>
      <ogr:Illiteracy>0.9</ogr:Illiteracy>
      <ogr:Life.Exp>70.63</ogr:Life.Exp>
      <ogr:Murder>11.1</ogr:Murder>
      <ogr:HS.Grad>52.8</ogr:HS.Grad>
      <ogr:Frost>125</ogr:Frost>
      <ogr:Area>56817</ogr:Area>
      <ogr:Name>Michigan</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F22">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-94.604299999999995,46.3943</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>3921</ogr:Population>
      <ogr:Income>4675</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>72.96</ogr:Life.Exp>
      <ogr:Murder>2.3</ogr:Murder>
      <ogr:HS.Grad>57.6</ogr:HS.Grad>
      <ogr:Frost>160</ogr:Frost>
      <ogr:Area>79289</ogr:Area>
      <ogr:Name>Minnesota</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F23">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-89.8065,32.675800000000002</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2341</ogr:Population>
      <ogr:Income>3098</ogr:Income>
      <ogr:Illiteracy>2.4</ogr:Illiteracy>
      <ogr:Life.Exp>68.09</ogr:Life.Exp>
      <ogr:Murder>12.5</ogr:Murder>
      <ogr:HS.Grad>41</ogr:HS.Grad>
      <ogr:Frost>50</ogr:Frost>
      <ogr:Area>47296</ogr:Area>
      <ogr:Name>Mississippi</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F24">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-92.5137,38.334699999999998</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>4767</ogr:Population>
      <ogr:Income>4254</ogr:Income>
      <ogr:Illiteracy>0.8</ogr:Illiteracy>
      <ogr:Life.Exp>70.69</ogr:Life.Exp>
      <ogr:Murder>9.3</ogr:Murder>
      <ogr:HS.Grad>48.8</ogr:HS.Grad>
      <ogr:Frost>108</ogr:Frost>
      <ogr:Area>68995</ogr:Area>
      <ogr:Name>Missouri</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F25">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-109.319999999999993,46.823</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>746</ogr:Population>
      <ogr:Income>4347</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>70.56</ogr:Life.Exp>
      <ogr:Murder>5</ogr:Murder>
      <ogr:HS.Grad>59.2</ogr:HS.Grad>
      <ogr:Frost>155</ogr:Frost>
      <ogr:Area>145587</ogr:Area>
      <ogr:Name>Montana</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F26">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-99.589799999999997,41.335599999999999</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>1544</ogr:Population>
      <ogr:Income>4508</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>72.6</ogr:Life.Exp>
      <ogr:Murder>2.9</ogr:Murder>
      <ogr:HS.Grad>59.3</ogr:HS.Grad>
      <ogr:Frost>139</ogr:Frost>
      <ogr:Area>76483</ogr:Area>
      <ogr:Name>Nebraska</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F27">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-116.850999999999999,39.106299999999997</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>590</ogr:Population>
      <ogr:Income>5149</ogr:Income>
      <ogr:Illiteracy>0.5</ogr:Illiteracy>
      <ogr:Life.Exp>69.03</ogr:Life.Exp>
      <ogr:Murder>11.5</ogr:Murder>
      <ogr:HS.Grad>65.2</ogr:HS.Grad>
      <ogr:Frost>188</ogr:Frost>
      <ogr:Area>109889</ogr:Area>
      <ogr:Name>Nevada</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F28">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-71.392399999999995,43.3934</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>812</ogr:Population>
      <ogr:Income>4281</ogr:Income>
      <ogr:Illiteracy>0.7</ogr:Illiteracy>
      <ogr:Life.Exp>71.23</ogr:Life.Exp>
      <ogr:Murder>3.3</ogr:Murder>
      <ogr:HS.Grad>57.6</ogr:HS.Grad>
      <ogr:Frost>174</ogr:Frost>
      <ogr:Area>9027</ogr:Area>
      <ogr:Name>New Hampshire</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F29">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-74.233599999999996,39.963700000000003</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>7333</ogr:Population>
      <ogr:Income>5237</ogr:Income>
      <ogr:Illiteracy>1.1</ogr:Illiteracy>
      <ogr:Life.Exp>70.93</ogr:Life.Exp>
      <ogr:Murder>5.2</ogr:Murder>
      <ogr:HS.Grad>52.5</ogr:HS.Grad>
      <ogr:Frost>115</ogr:Frost>
      <ogr:Area>7521</ogr:Area>
      <ogr:Name>New Jersey</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F30">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-105.941999999999993,34.476399999999998</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>1144</ogr:Population>
      <ogr:Income>3601</ogr:Income>
      <ogr:Illiteracy>2.2</ogr:Illiteracy>
      <ogr:Life.Exp>70.32</ogr:Life.Exp>
      <ogr:Murder>9.7</ogr:Murder>
      <ogr:HS.Grad>55.2</ogr:HS.Grad>
      <ogr:Frost>120</ogr:Frost>
      <ogr:Area>121412</ogr:Area>
      <ogr:Name>New Mexico</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F31">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-75.144900000000007,43.136099999999999</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>18076</ogr:Population>
      <ogr:Income>4903</ogr:Income>
      <ogr:Illiteracy>1.4</ogr:Illiteracy>
      <ogr:Life.Exp>70.55</ogr:Life.Exp>
      <ogr:Murder>10.9</ogr:Murder>
      <ogr:HS.Grad>52.7</ogr:HS.Grad>
      <ogr:Frost>82</ogr:Frost>
      <ogr:Area>47831</ogr:Area>
      <ogr:Name>New York</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F32">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-78.468599999999995,35.419499999999999</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>5441</ogr:Population>
      <ogr:Income>3875</ogr:Income>
      <ogr:Illiteracy>1.8</ogr:Illiteracy>
      <ogr:Life.Exp>69.21</ogr:Life.Exp>
      <ogr:Murder>11.1</ogr:Murder>
      <ogr:HS.Grad>38.5</ogr:HS.Grad>
      <ogr:Frost>80</ogr:Frost>
      <ogr:Area>48798</ogr:Area>
      <ogr:Name>North Carolina</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F33">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-100.099000000000004,47.2517</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>637</ogr:Population>
      <ogr:Income>5087</ogr:Income>
      <ogr:Illiteracy>0.8</ogr:Illiteracy>
      <ogr:Life.Exp>72.78</ogr:Life.Exp>
      <ogr:Murder>1.4</ogr:Murder>
      <ogr:HS.Grad>50.3</ogr:HS.Grad>
      <ogr:Frost>186</ogr:Frost>
      <ogr:Area>69273</ogr:Area>
      <ogr:Name>North Dakota</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F34">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-82.596299999999999,40.220999999999997</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>10735</ogr:Population>
      <ogr:Income>4561</ogr:Income>
      <ogr:Illiteracy>0.8</ogr:Illiteracy>
      <ogr:Life.Exp>70.82</ogr:Life.Exp>
      <ogr:Murder>7.4</ogr:Murder>
      <ogr:HS.Grad>53.2</ogr:HS.Grad>
      <ogr:Frost>124</ogr:Frost>
      <ogr:Area>40975</ogr:Area>
      <ogr:Name>Ohio</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F35">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-97.123900000000006,35.505299999999998</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2715</ogr:Population>
      <ogr:Income>3983</ogr:Income>
      <ogr:Illiteracy>1.1</ogr:Illiteracy>
      <ogr:Life.Exp>71.42</ogr:Life.Exp>
      <ogr:Murder>6.4</ogr:Murder>
      <ogr:HS.Grad>51.6</ogr:HS.Grad>
      <ogr:Frost>82</ogr:Frost>
      <ogr:Area>68782</ogr:Area>
      <ogr:Name>Oklahoma</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F36">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-120.067999999999998,43.907800000000002</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2284</ogr:Population>
      <ogr:Income>4660</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>72.13</ogr:Life.Exp>
      <ogr:Murder>4.2</ogr:Murder>
      <ogr:HS.Grad>60</ogr:HS.Grad>
      <ogr:Frost>44</ogr:Frost>
      <ogr:Area>96184</ogr:Area>
      <ogr:Name>Oregon</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F37">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-77.450000000000003,40.9069</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>11860</ogr:Population>
      <ogr:Income>4449</ogr:Income>
      <ogr:Illiteracy>1</ogr:Illiteracy>
      <ogr:Life.Exp>70.43</ogr:Life.Exp>
      <ogr:Murder>6.1</ogr:Murder>
      <ogr:HS.Grad>50.2</ogr:HS.Grad>
      <ogr:Frost>126</ogr:Frost>
      <ogr:Area>44966</ogr:Area>
      <ogr:Name>Pennsylvania</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F38">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-71.124399999999994,41.592799999999997</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>931</ogr:Population>
      <ogr:Income>4558</ogr:Income>
      <ogr:Illiteracy>1.3</ogr:Illiteracy>
      <ogr:Life.Exp>71.9</ogr:Life.Exp>
      <ogr:Murder>2.4</ogr:Murder>
      <ogr:HS.Grad>46.4</ogr:HS.Grad>
      <ogr:Frost>127</ogr:Frost>
      <ogr:Area>1049</ogr:Area>
      <ogr:Name>Rhode Island</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F39">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-80.5056,33.619</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>2816</ogr:Population>
      <ogr:Income>3635</ogr:Income>
      <ogr:Illiteracy>2.3</ogr:Illiteracy>
      <ogr:Life.Exp>67.96</ogr:Life.Exp>
      <ogr:Murder>11.6</ogr:Murder>
      <ogr:HS.Grad>37.8</ogr:HS.Grad>
      <ogr:Frost>65</ogr:Frost>
      <ogr:Area>30225</ogr:Area>
      <ogr:Name>South Carolina</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F40">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-99.723799999999997,44.3365</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>681</ogr:Population>
      <ogr:Income>4167</ogr:Income>
      <ogr:Illiteracy>0.5</ogr:Illiteracy>
      <ogr:Life.Exp>72.08</ogr:Life.Exp>
      <ogr:Murder>1.7</ogr:Murder>
      <ogr:HS.Grad>53.3</ogr:HS.Grad>
      <ogr:Frost>172</ogr:Frost>
      <ogr:Area>75955</ogr:Area>
      <ogr:Name>South Dakota</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F41">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-86.456000000000003,35.676699999999997</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>4173</ogr:Population>
      <ogr:Income>3821</ogr:Income>
      <ogr:Illiteracy>1.7</ogr:Illiteracy>
      <ogr:Life.Exp>70.11</ogr:Life.Exp>
      <ogr:Murder>11</ogr:Murder>
      <ogr:HS.Grad>41.8</ogr:HS.Grad>
      <ogr:Frost>70</ogr:Frost>
      <ogr:Area>41328</ogr:Area>
      <ogr:Name>Tennessee</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F42">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-98.785700000000006,31.3897</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>12237</ogr:Population>
      <ogr:Income>4188</ogr:Income>
      <ogr:Illiteracy>2.2</ogr:Illiteracy>
      <ogr:Life.Exp>70.9</ogr:Life.Exp>
      <ogr:Murder>12.2</ogr:Murder>
      <ogr:HS.Grad>47.4</ogr:HS.Grad>
      <ogr:Frost>35</ogr:Frost>
      <ogr:Area>262134</ogr:Area>
      <ogr:Name>Texas</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F43">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-111.329999999999998,39.106299999999997</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>1203</ogr:Population>
      <ogr:Income>4022</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>72.9</ogr:Life.Exp>
      <ogr:Murder>4.5</ogr:Murder>
      <ogr:HS.Grad>67.3</ogr:HS.Grad>
      <ogr:Frost>137</ogr:Frost>
      <ogr:Area>82096</ogr:Area>
      <ogr:Name>Utah</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F44">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-72.545000000000002,44.250799999999998</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>472</ogr:Population>
      <ogr:Income>3907</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>71.64</ogr:Life.Exp>
      <ogr:Murder>5.5</ogr:Murder>
      <ogr:HS.Grad>57.1</ogr:HS.Grad>
      <ogr:Frost>168</ogr:Frost>
      <ogr:Area>9267</ogr:Area>
      <ogr:Name>Vermont</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F45">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-78.200500000000005,37.563000000000002</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>4981</ogr:Population>
      <ogr:Income>4701</ogr:Income>
      <ogr:Illiteracy>1.4</ogr:Illiteracy>
      <ogr:Life.Exp>70.08</ogr:Life.Exp>
      <ogr:Murder>9.5</ogr:Murder>
      <ogr:HS.Grad>47.8</ogr:HS.Grad>
      <ogr:Frost>85</ogr:Frost>
      <ogr:Area>39780</ogr:Area>
      <ogr:Name>Virginia</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F46">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-119.745999999999995,47.423099999999998</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>3559</ogr:Population>
      <ogr:Income>4864</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>71.72</ogr:Life.Exp>
      <ogr:Murder>4.3</ogr:Murder>
      <ogr:HS.Grad>63.5</ogr:HS.Grad>
      <ogr:Frost>32</ogr:Frost>
      <ogr:Area>66570</ogr:Area>
      <ogr:Name>Washington</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F47">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-80.666499999999999,38.4204</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>1799</ogr:Population>
      <ogr:Income>3617</ogr:Income>
      <ogr:Illiteracy>1.4</ogr:Illiteracy>
      <ogr:Life.Exp>69.48</ogr:Life.Exp>
      <ogr:Murder>6.7</ogr:Murder>
      <ogr:HS.Grad>41.6</ogr:HS.Grad>
      <ogr:Frost>100</ogr:Frost>
      <ogr:Area>24070</ogr:Area>
      <ogr:Name>West Virginia</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F48">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-89.994100000000003,44.593699999999998</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>4589</ogr:Population>
      <ogr:Income>4468</ogr:Income>
      <ogr:Illiteracy>0.7</ogr:Illiteracy>
      <ogr:Life.Exp>72.48</ogr:Life.Exp>
      <ogr:Murder>3</ogr:Murder>
      <ogr:HS.Grad>54.5</ogr:HS.Grad>
      <ogr:Frost>149</ogr:Frost>
      <ogr:Area>54464</ogr:Area>
      <ogr:Name>Wisconsin</ogr:Name>
    </ogr:state>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:state fid="F49">
      <ogr:geometryProperty><gml:Point><gml:coordinates>-107.256,43.050400000000003</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:Population>376</ogr:Population>
      <ogr:Income>4566</ogr:Income>
      <ogr:Illiteracy>0.6</ogr:Illiteracy>
      <ogr:Life.Exp>70.29</ogr:Life.Exp>
      <ogr:Murder>6.9</ogr:Murder>
      <ogr:HS.Grad>62.9</ogr:HS.Grad>
      <ogr:Frost>173</ogr:Frost>
      <ogr:Area>97203</ogr:Area>
      <ogr:Name>Wyoming</ogr:Name>
    </ogr:state>
  </gml:featureMember>
</ogr:FeatureCollection>
